# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splash_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(342, 339)
        self.centralwidget = QtWidgets.QWidget(SplashScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.circularProgressBarBase = QtWidgets.QFrame(self.centralwidget)
        self.circularProgressBarBase.setGeometry(QtCore.QRect(10, 10, 331, 331))
        self.circularProgressBarBase.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circularProgressBarBase.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularProgressBarBase.setObjectName("circularProgressBarBase")
        self.circularBg = QtWidgets.QFrame(self.circularProgressBarBase)
        self.circularBg.setGeometry(QtCore.QRect(10, 10, 300, 300))
        self.circularBg.setStyleSheet("QFrame{\n"
"    border-radius: 150px;\n"
"    background-color: rgba(77, 77, 127, 120);\n"
"}")
        self.circularBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circularBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularBg.setObjectName("circularBg")
        self.circularProgress = QtWidgets.QFrame(self.circularBg)
        self.circularProgress.setGeometry(QtCore.QRect(0, 0, 301, 311))
        self.circularProgress.setStyleSheet("QFrame{\n"
"    border-radius: 150px;\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.749 rgba(255, 0, 127, 0), stop:0.750 rgba(85, 170, 255, 255));\n"
"}")
        self.circularProgress.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circularProgress.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularProgress.setObjectName("circularProgress")
        self.container = QtWidgets.QFrame(self.circularProgress)
        self.container.setGeometry(QtCore.QRect(10, 10, 281, 281))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.container.setFont(font)
        self.container.setStyleSheet("QFrame{\n"
"    border-radius: 135px;\n"
"    background-color: rgb(77, 77, 127);\n"
"}")
        self.container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.labelCredits = QtWidgets.QLabel(self.container)
        self.labelCredits.setGeometry(QtCore.QRect(20, 20, 238, 43))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labelCredits.setFont(font)
        self.labelCredits.setStyleSheet("background-color: none;\n"
"color: rgb(155, 155, 255);")
        self.labelCredits.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCredits.setObjectName("labelCredits")
        self.labelLoadingInfo = QtWidgets.QLabel(self.container)
        self.labelLoadingInfo.setGeometry(QtCore.QRect(70, 190, 140, 20))
        self.labelLoadingInfo.setMinimumSize(QtCore.QSize(0, 20))
        self.labelLoadingInfo.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.labelLoadingInfo.setFont(font)
        self.labelLoadingInfo.setStyleSheet("QLabel{\n"
"background-color: rgb(93, 93, 154);\n"
"border-radius:10;\n"
"    color: #FFFFFF;\n"
"\n"
"}")
        self.labelLoadingInfo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelLoadingInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLoadingInfo.setObjectName("labelLoadingInfo")
        self.labelTitle = QtWidgets.QLabel(self.container)
        self.labelTitle.setGeometry(QtCore.QRect(40, 190, 211, 81))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitle.setFont(font)
        self.labelTitle.setStyleSheet("background-color: none;\n"
"color: #FFFFFF")
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setWordWrap(True)
        self.labelTitle.setObjectName("labelTitle")
        self.labelPercentage = QtWidgets.QLabel(self.container)
        self.labelPercentage.setGeometry(QtCore.QRect(30, 60, 211, 121))
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(46)
        self.labelPercentage.setFont(font)
        self.labelPercentage.setStyleSheet("background-color: none;\n"
"color: #FFFFFF")
        self.labelPercentage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPercentage.setObjectName("labelPercentage")
        SplashScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashScreen)
        QtCore.QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QtCore.QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "MainWindow"))
        self.labelCredits.setText(_translate("SplashScreen", "by: GPG CO6I STUDENTS"))
        self.labelLoadingInfo.setText(_translate("SplashScreen", "loading..."))
        self.labelTitle.setText(_translate("SplashScreen", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">IoT Based Attendance System Using Face Detection</span></p></body></html>"))
        self.labelPercentage.setText(_translate("SplashScreen", "<html><head/><body><p><span style=\" font-size:48pt;\">0</span><span style=\" font-size:48pt; vertical-align:super;\">%</span></p></body></html>"))



