# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'warn.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import QMovie
import subprocess
import sys
import platform

from PyQt5.QtWidgets import *
class Ui_Form(object):
    def setupUi(self, Form):
        
        
        Form.setObjectName("Form")
        Form.resize(1381, 671)
        Form.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 842, 534))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"Border-radius:10")

        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.movie = QMovie("connect-camera.gif")
        self.label.setMovie(self.movie)
  
        self.startAnimation()
  
       

        
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(880, 20, 431, 331))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("usbcam.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 570, 1311, 41))
        font = QtGui.QFont()
        font.setFamily("Office")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"Border-radius:10;\n"
"color: rgb(0, 99, 148);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(620, 620, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Office")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(75, 151, 227);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(Form.close)



        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Hardware Assembling Guideline Page"))
        self.label_3.setText(_translate("Form", "Before We Move Forward Check Whether Raspberry Cam or USB Cam is Attached Correctly to Raspberry-Pi as Per Displayed in above images "))
        self.pushButton.setText(_translate("Form", "OK"))
       
     # Start Animation
  
    def startAnimation(self):
        self.movie.start()
  
    # Stop Animation(According to need)
    def stopAnimation(self):
        self.movie.stop()
   
    

   
  
      
      
       

       
       



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
